#!/usr/bin/env python3
"""Generate a kinematic perturbation YAML for the simulated ground truth.

The file this writes is consumed by calibration_sim.launch.py, which bakes it
into the URDF that Gazebo spawns while robot_state_publisher keeps the nominal
one. WP4 then has a real error to identify whose true value is known exactly.

Usage:
    generate_perturbation.py --seed 42 --t-sigma 0.001 --r-sigma-deg 0.1 \
        -o config/perturbations/example_1mm.yaml
    generate_perturbation.py --zero -o config/perturbations/zero.yaml
"""
import argparse
import os
import sys

import numpy as np
import yaml

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                os.pardir, os.pardir, 'annin_ar4_calibration'))

from annin_ar4_calibration.core import kinematic_model, perturbation  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--t-sigma', type=float, default=0.001,
                        help='per-coefficient translation sigma, metres')
    parser.add_argument('--r-sigma-deg', type=float, default=0.1,
                        help='per-coefficient rotation sigma, degrees')
    parser.add_argument('--t-clip', type=float, default=0.002,
                        help='hard clip on translation coefficients, metres')
    parser.add_argument('--r-clip-deg', type=float, default=0.15,
                        help='hard clip on rotation coefficients, degrees')
    parser.add_argument('--zero', action='store_true',
                        help='emit an all-zero perturbation (the unperturbed baseline)')
    parser.add_argument('-o', '--output', required=True)
    return parser.parse_args()


def main():
    args = parse_args()
    n_joints = len(perturbation.DEFAULT_JOINT_NAMES)
    corrections = np.zeros((n_joints, kinematic_model.PARAMS_PER_JOINT))

    if args.zero:
        described = 'all-zero baseline (unperturbed reference run)'
        command = 'generate_perturbation.py --zero'
    else:
        rng = np.random.default_rng(args.seed)
        corrections[:, 0:2] = np.clip(
            rng.normal(0.0, args.t_sigma, (n_joints, 2)), -args.t_clip, args.t_clip)
        r_clip = np.radians(args.r_clip_deg)
        corrections[:, 2:4] = np.clip(
            rng.normal(0.0, np.radians(args.r_sigma_deg), (n_joints, 2)), -r_clip, r_clip)
        described = (f'seed={args.seed}, t_sigma={args.t_sigma} m, '
                     f'r_sigma={args.r_sigma_deg} deg')
        command = (f'generate_perturbation.py --seed {args.seed} '
                   f'--t-sigma {args.t_sigma} --r-sigma-deg {args.r_sigma_deg}')

    document = perturbation.to_yaml_dict(
        corrections,
        generated_by=command,
        description=described,
        parameterization=(
            'Identical to annin_ar4_calibration.core.kinematic_model: per joint, '
            'delta_t_perp and delta_r_perp are 2 coefficients each in that joint\'s '
            'own orthogonal_basis(axis). dT = Trans(delta_t) @ Rot(delta_r) and the '
            'URDF origin becomes T0 @ dT, so these numbers are directly comparable '
            "to kinematic_result.yaml's recovered corrections with no conversion."),
    )

    os.makedirs(os.path.dirname(os.path.abspath(args.output))
                or '.', exist_ok=True)
    with open(args.output, 'w') as f:
        f.write('# Generated by generate_perturbation.py - do not edit by hand.\n')
        yaml.safe_dump(document, f, sort_keys=False, default_flow_style=None)

    worst_t = np.abs(corrections[:, 0:2]).max() * 1000
    worst_r = np.degrees(np.abs(corrections[:, 2:4]).max())
    print(f'wrote {args.output}')
    print(f'  {described}')
    print(
        f'  largest coefficient: {worst_t:.3f} mm translation, {worst_r:.4f} deg rotation')


if __name__ == '__main__':
    main()
