hand_eye_collector:
  ros__parameters:
    num_candidate_poses: 60
    min_samples: 10
hand_eye_calibration:
  ros__parameters:
    min_samples: 10
kinematic_collector:
  ros__parameters:
    num_candidate_configs: 60
    min_samples: 10
    max_sequence_duration_sec: 3420.0
kinematic_calibration:
  ros__parameters:
    min_samples: 12
